CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,

    games INTEGER NOT NULL DEFAULT 0,

    TTT_games INTEGER NOT NULL DEFAULT 0,
    bingo_games INTEGER NOT NULL DEFAULT 0,
    chess_games INTEGER NOT NULL DEFAULT 0,

    lost INTEGER NOT NULL DEFAULT 0,
    wins INTEGER NOT NULL DEFAULT 0,

    TTT_lost INTEGER NOT NULL DEFAULT 0,
    bingo_lost INTEGER NOT NULL DEFAULT 0,
    chess_lost INTEGER NOT NULL DEFAULT 0,

    TTT_win INTEGER NOT NULL DEFAULT 0,
    bingo_win INTEGER NOT NULL DEFAULT 0,
    chess_win INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE users
ADD COLUMN password TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN otp TEXT;
ALTER TABLE users ADD COLUMN otp_expires_at INTEGER;
ALTER TABLE users ADD COLUMN verified INTEGER NOT NULL DEFAULT 0;